### ISSUE TITLE
Unicode error

### ISSUE THREAD

**Issue by robinandeer** [moonso/query_phenomizer#1]
From Scout

``` python
2016-02-05 07:25:14,915 - scout - ERROR: Exception on /cust000/245279-2/phenotype_terms [POST] [in /home/scout/miniconda/envs/prod/lib/python2.7/site-packages/flask/app.py:1423]
Traceback (most recent call last):
 File "/home/scout/miniconda/envs/prod/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
   response = self.full_dispatch_request()
 File "/home/scout/miniconda/envs/prod/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
   rv = self.handle_user_exception(e)
 File "/home/scout/miniconda/envs/prod/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
   reraise(exc_type, exc_value, tb)
 File "/home/scout/miniconda/envs/prod/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
   rv = self.dispatch_request()
 File "/home/scout/miniconda/envs/prod/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
   return self.view_functions[rule.endpoint](**req.view_args)
 File "/home/scout/components/scout/src/scout/scout/core/views.py", line 196, in case_phenotype
   genes = hpo_genes(case_model.phenotype_terms)
 File "/home/scout/components/scout/src/scout/scout/core/views.py", line 225, in hpo_genes
   results = query_phenomizer.query(hpo_terms)
 File "/home/scout/miniconda/envs/prod/lib/python2.7/site-packages/query_phenomizer/utils.py", line 125, in query
   parsed_terms.append(parse_result(line))
 File "/home/scout/miniconda/envs/prod/lib/python2.7/site-packages/query_phenomizer/utils.py", line 55, in parse_result
   result_line = line.rstrip().split('\t')
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 25: ordinal not in range(128)
```

**Comment by moonso** [comment]
Ahh I can not replicate this error!!!
